development:
  sessions:
    default:
      database: testables_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: testables_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
